api_key_file_path: gemini_api_key.txt

# reasoning on input parameters
brain_model_name: gemini-2.0-flash

# text-to-speech conversion parameters
tts_model_name: gemini-2.5-flash-preview-tts
tts_voice_name: Kore,
save_audio_file: false
