verbose: 0

# run get_index.py to get index
# TODO: can be automated?
device_index: 11

# ReSpeaker 4-Mic Array v2.0 identification numbers
vendor_id: 0x2886
product_id: 0x0018

# if a voice was detected and a recording started, if no voice is detected for this duration, the recording will stop
max_silence_duration: 3

# whether to save audio files recorded by the microphone listener
save_file: True

# audio stream configuration
stream_params:
  # audio sample rate in Hz
  sample_rate: 16000
  # chunk size in samples
  chunk_size: 1024
  # number of channels
  channels: 1
  # width of each sample in bytes
  width: 2
