verbose: 0

# run get_index.py to get index
# TODO: can be automated?
index: 11

# ReSpeaker 4-Mic Array v2.0 identification numbers
vendor_id: 0x2886
product_id: 0x0018

# if a voice was detected and a recording started, if no voice is detected for this duration, the recording will stop
max_silence_duration: 2