verbose: 0
# api key for google ai studio
api_key_file_path: /home/jetson/GIT/voice_robot_interaction/google_ai_studio/gemini_api_key.txt

use_tts_service: False

# parameters for reasoning (reasoning_service)
reasoning_parameters:
#  model_name: gemini-2.0-flash
  model_name: gemini-2.5-flash
  prompt_template: You are an AI that pilots a real robot with four wheels and one arm. Depending on user's requests
    you should respond with natural language (but keep the response short) or a function call as appropriate.
  mime_type: audio/wav
  remember_history: True

# parameters for text-to-speech (tts_service)
tts_parameters:
  model_name: gemini-2.5-flash-preview-tts
  voice_name: kore
  save_file: False